/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_android_framebufferizer_NativeRenderer */

#ifndef _Included_com_android_framebufferizer_NativeRenderer
#define _Included_com_android_framebufferizer_NativeRenderer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_android_framebufferizer_NativeRenderer
 * Method:    setDeviceInfo
 * Signature: (IIIDD)I
 */
JNIEXPORT jint JNICALL Java_com_android_framebufferizer_NativeRenderer_setDeviceInfo(
    JNIEnv*, jclass, jint, jint, jint, jdouble, jdouble);

/*
 * Class:     com_android_framebufferizer_NativeRenderer
 * Method:    renderBuffer
 * Signature: (IIIII[I)I
 */
JNIEXPORT jint JNICALL Java_com_android_framebufferizer_NativeRenderer_renderBuffer(
    JNIEnv*, jclass, jint, jint, jint, jint, jint, jintArray);

#ifdef __cplusplus
}
#endif
#endif
